### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by rwb196884** [browserslist/caniuse-lite#126]
I've found this installed in a project that I've inherited, but I can't find it referenced in the code. Doesn't seem to do anything.

What is it? The `README.md` doesn't say and nor does `caniuse.com`.

**Comment by ai** [comment]
This dependency is re-pack of `caniuse-db`, the `caniuse.com` in JSON form in npm package. We need this re-pack to have smaller `node_modules`.

Very likely that you have this dependency because of Autoprefixer, Browserslist, or Babel. Any tool that need latest browser data, for instance, to add polyfills.
