### ISSUE TITLE
I am a beginner, and I have a big problem. This project is an old one. Who can help me?

### ISSUE THREAD

**Issue by createjdd** [browserslist/caniuse-lite#130]
I made a mistake? Why is this dependency so large? Is there anyone who can help me a bit? Thank you very much.
<img width="412" alt="image" src="https://github.com/user-attachments/assets/ee8c85ec-fefc-47ab-a505-427c731d0db4">

**Comment by ai** [comment]
It is really so large, because it contains all data from Can I Use website.

Uncompressed version (`caniuse-db`) is even bigger (20 MB) https://www.npmjs.com/package/caniuse-db

But you should not use in client-side JS bundle for web. This dependency is mostly for Node.js CLI tools like Autoprefixer (where size is not so painful).
