### ISSUE TITLE
1.0.30001304 breaks angular-builds

### ISSUE THREAD

**Issue by StefanMuellerCH** [browserslist/caniuse-lite#92]
After upgrading from second-latest to latest version 1.0.30001304 of caniuse-lite, angular-builds fail with this error:

`
> ng build

√ Browser application bundle generation complete.
An unhandled exception occurred: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
See "C:\Temp\ng-opy9zE\angular-errors.log" for further details.
`

Manually setting the old version in package.json fixes the build:
    "caniuse-lite": "1.0.30001303"

**Comment by ai** [comment]
Can you show the full log?

**Comment by StefanMuellerCH** [comment]
Full log if it helps (doesnt help me :-))

`
[error] HookWebpackError: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
    at makeWebpackError (D:\Working\ng13-new-breaking\my-app\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at D:\Working\ng13-new-breaking\my-app\node_modules\webpack\lib\Compilation.js:3055:12
    at eval (eval at create (D:\Working\ng13-new-breaking\my-app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:98:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"
    at failureErrorWithLog (D:\Working\ng13-new-breaking\my-app\node_modules\esbuild\lib\main.js:1557:15)
    at D:\Working\ng13-new-breaking\my-app\node_modules\esbuild\lib\main.js:1346:29
    at D:\Working\ng13-new-breaking\my-app\node_modules\esbuild\lib\main.js:637:9
    at handleIncomingPacket (D:\Working\ng13-new-breaking\my-app\node_modules\esbuild\lib\main.js:734:9)
    at Socket.readFromStdout (D:\Working\ng13-new-breaking\my-app\node_modules\esbuild\lib\main.js:604:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

`

**Comment by ai** [comment]
You need to open an issue in `esbuild`.

`15.2-15.3` is a valid Can I Use version. They recently changed version and `esbuild` need to fix code for new data.

I can’t change the version here because we are just repack of Can I Use data.

@evanw if you need any help I can assist you. Unfortunately, Can I Use browser’s versions are inconsistent and has these combined versions (they have it for Safari before).

**Comment by evanw** [comment]
>  error: Invalid version: "15.2-15.3"

A valid version number for esbuild is one to three numbers separated by dots (i.e. `^\d+(\.\d+){0,2}$`). The string `15.2-15.3` is an invalid version number for esbuild because it is not one to three numbers separated by dots.

**Comment by ai** [comment]
@evanw I know, but this how Can I Use track data.

1. It was before `15.2-15.3` release. There are a few old `X.X-Y.Y` releases in Safari stats for years.
2. Can I Use also have non-digit versions. For instance, `Safari TP` or `op_mini all`.
3. I asked Can I Use team to avoid this non-standard versions without any results.

Maybe the simplest way is:

```js
if (version.includes('-')) {
  version = version.split('.')[0]
}
```

We can add some helper to Browserslist. Tell me where do you use this version and what API will be better for you.

**Comment by evanw** [comment]
> Maybe the simplest way is:
> 
> ```js
> if (version.includes('-')) {
>   version = version.split('.')[0]
> }
> ```
> We can add some helper to Browserslist. Tell me where do you use this version and what API will be better for you.

You don't need to modify esbuild to do this. You can just do this yourself before passing your data to esbuild's [target](https://esbuild.github.io/api/#target) setting.

> 2. Can I Use also have non-digit versions. For instance, `Safari TP` or `op_mini all`.

These don't specify a specific version. You can't unambiguously map these strings to a specific binary executable, so they can't be considered a valid version number for esbuild.

Regarding `Safari TP`: Even though you can hypothetically map to a specific release of Safari Technology Preview (e.g.  Safari Technology Preview 137), I don't think it makes sense for esbuild to support browser compatibility data for prerelease software, since it's not something that real users would use.

Regarding `op_mini`: I don't have separate compatibility data for Opera because the underlying engine has been Chrome for almost a decade and I have never seen Opera listed as a supported browser version for any piece of software. I could see the argument for adding it to esbuild though. But in that case you'd still have to pass a specific version of Opera, not just `all`. You could pass in the version number `0` to trigger esbuild to sort of indicate "all" I suppose. That would just disable all of the syntax features that esbuild supports (which then isn't anything specific to Opera).

**Comment by ai** [comment]
> You don't need to modify esbuild to do this. You can just do this yourself before passing your data to esbuild's target setting.

Am I right that `esbuild` do not use Browserslist or `caniuse-data` and version was passed by some @StefanMuellerCH script?

In this case, of course, there is no issue in `esbuild` and `target` generation script should by fixed.

**Comment by ai** [comment]
> I don't have separate compatibility data for Opera because the underlying engine has been Chrome f

@evanw just to clarification, Opera ≠ Opera Mini. Opera Mini was a very special browser for future phones (which was popular before smartphones). Because of limitations, they render a page on the server and send to the phone in a special image-like format.

This server-side page renderer was not in ported to Chrome, but in the reality it is almost dead right now.

The most popular feature [no-smartphone] phone uses Firefox port nowadays.

**Comment by evanw** [comment]
> Am I right that `esbuild` do not use Browserslist or `caniuse-data` and version was passed by some @StefanMuellerCH script?

Yes esbuild has nothing to do with browserslist or `caniuse-data`. The compatibility data in esbuild comes from https://kangax.github.io/compat-table/es6/. People wanting to use browserslist with esbuild need to convert the browserslist query into specific browsers and version numbers meant for esbuild like this: https://esbuild.github.io/api/#target.

> @evanw just to clarification, Opera ≠ Opera Mini. Opera Mini was a very special browser for future phones (which was popular before smartphones). Because of limitations, they render a page on the server and send to the phone in a special image-like format.

Ah, I see. I did not know that. There's no Opera Mini on https://kangax.github.io/compat-table/es6/ but there is something called Opera Mobile. Not sure if that's the same thing or not.

**Comment by ai** [comment]
> There's no Opera Mini on https://kangax.github.io/compat-table/es6/ but there is something called Opera Mobile. Not sure if that's the same thing or not.

Opera Mobile was a different browser. It was the port of desktop Opera to smartphone. No server render magic.

It became a clone of Chrome at some point.
